### ISSUE TITLE
Google Analytics blocks page load

### ISSUE THREAD

**Issue by sman591** [ritstudentgovernment/OpenEvals#22]
When loading OpenEvals, if Google Analytics is being slow (such as `google-analytics.com` going down), the website will just sit there and wait with a blank screen.

This can easily be fixed by moving google analytics into the `<body>` of the html (optimally the very bottom).

**Comment by brandonhudson** [comment]
https://github.com/ritstudentgovernment/OpenEvals/pull/23 partially fixes this issue, but we cannot seem to find where the google-analytics.com dependency is being added.

**Comment by NathanCastle** [comment]
Google Analytics was added directly to the production version.

Are you having problems with this or are you addressing the theoretical possibility?

**Comment by sman591** [comment]
The issue just happened to me - Google's DNS was hung up, so the page waited until it could resolve

**Comment by NathanCastle** [comment]
Interesting, I didn't realize that happened. I made the change in production and I'll make sure that analytics code isn't in the head in the future. 

Thanks for the fix! :)
